### ISSUE TITLE
Al correr las pruebas en docker crashea

### ISSUE THREAD

**Issue by diegokim** [seguijoaquin/taller2-sharedserver#45]
{ [error: no PostgreSQL user name specified in startup packet]
  name: 'error',
  length: 114,
  severity: 'FATAL',
  code: '28000',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postmaster.c',
  line: '2074',
  routine: 'ProcessStartupPacket' }
_http_server.js:190
  var statusLine = 'HTTP/1.1 ' + statusCode.toString() + ' ' +
                                           ^

TypeError: Cannot read property 'toString' of undefined
    at ServerResponse.writeHead (_http_server.js:190:44)
    at ServerResponse.writeHead (/home/taller2-sharedserver/node_modules/morgan/node_modules/on-headers/index.js:55:19)
    at ServerResponse._implicitHeader (_http_server.js:157:8)
    at ServerResponse.OutgoingMessage.end (_http_outgoing.js:573:10)
    at ServerResponse.send (/home/taller2-sharedserver/node_modules/express/lib/response.js:204:10)
    at ServerResponse.json (/home/taller2-sharedserver/node_modules/express/lib/response.js:249:15)
    at sendError (/home/taller2-sharedserver/handlers/db_handler.js:290:22)
    at /home/taller2-sharedserver/handlers/db_handler.js:14:21
    at /home/taller2-sharedserver/node_modules/pg/lib/pool.js:82:27
    at /home/taller2-sharedserver/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:339:9

npm ERR! Linux 4.1.19-boot2docker
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! t2shared@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the t2shared@0.0.0 start script 'node ./bin/www'.
npm ERR! This is most likely a problem with the t2shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs t2shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls t2shared
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/taller2-sharedserver/npm-debug.log

**Comment by diegokim** [comment]
Como armar la URL de la DB correctamente:

https://www.elephantsql.com/docs/nodejs.html

Como cambiar un password:

http://stackoverflow.com/questions/7695962/postgresql-password-authentication-failed-for-user-postgres
